version: '3.1'

services:

  db:
    image: postgres:12.1
    restart: always
    volumes:
      - lunchpicker-postgres:/var/lib/postgresql/data
    logging:
      driver: none
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: yourStrong(!)Password

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080

volumes:
  lunchpicker-postgres: