version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile

        volumes:
            - ..:/workspace:cached
            - /var/run/docker.sock:/var/run/docker.sock

        ports:
            - 3000:3000
            - 3001:3001

        command: sleep infinity

        links:
            - db

    db:
        image: postgres:12.1
        restart: always
        volumes:
            - lunchpicker-postgres:/var/lib/postgresql/data
        logging:
            driver: none
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: yourStrong(!)Password

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    lunchpicker-postgres:
